### ISSUE TITLE
Can you add Chinese option to the side bar please?

### ISSUE THREAD

**Issue by InstaTechHD** [Manj0tBenipal/kaido#6]

**Comment by Manj0tBenipal** [comment]
Can You explain the issue a bit? And if possible please add a screenchot of the location you are mentioning.  
The APIs only provide information in English. only the titles are availablein Japanese not Chinese.

**Comment by InstaTechHD** [comment]
Something like this

![Screenshot_2023-09-28-11-56-32-756-edit_com.android.chrome.jpg](https://github.com/Manj0tBenipal/kaido/assets/68559185/aa26d7be-4c5d-41a0-bff2-c671778fbbdd)

**Comment by Manj0tBenipal** [comment]
I'll read the API documentation and see if I find anything regarding the
language preference and let you know.

**Comment by InstaTechHD** [comment]
Sure

**Comment by Manj0tBenipal** [comment]
Sorry to disappoint you but there is no API endpoint for retrieving anime based on language. Moreover, different APIs are used for displaying anime and watching episodes. There is a possibility of conflict between these APIs. To explain it, one of the APIs might give a result for DUB anime but the DUB version of that anime may not be available in the API used for playing episodes.
But hey I can certainly add  seasons.

**Comment by InstaTechHD** [comment]
I understand
